language: common-lisp
sudo: required

env:
  matrix:
      - LISP=abcl
      - LISP=allegro
      
      # Error outside our control:
      # The command "curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash" failed and exited with 1 during .
      # - LISP=allegromodern
      
      - LISP=ccl
      - LISP=clisp
      
      # Error outside our control:
      # /home/travis/.cim/bin/cl: 9: .: Can't open /home/travis/.cim/config/current.7469
      # - LISP=cmucl
      
      - LISP=ecl
      - LISP=sbcl

install:
  # Install cl-travis
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash
  # Our project
  - git clone https://github.com/metawilm/cl-custom-hash-table.git ~/lisp/cl-custom-hash-table

script:
  - cl -e '(ql:quickload :cl-custom-hash-table)'
       -e '(ql:quickload :cl-custom-hash-table-test)'
       -e '(cl-custom-hash-table-test:run)'

notifications:
  email:
    - metawilm@gmail.com